shifts:
 channel: # Channel ID
 permissions: [] # Role IDs
 online: # Online Role ID
 break: # Break Role ID
 manager: [] # Manager Role Ids
 

punishments:
 channel: # Channel ID
 types: ['Warning', 'Kick', 'Ban']
 permissions: [] # Role Ids
 
 


